name: Build APK v1.2
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: PWABuilder Action - Generate APK
        uses: pwa-builder/pwa-builder-action@v2.2.0
        with:
          url: 'https://MundDev.github.io/fuga-de-resonancia/'
          manifest_url: 'https://MundDev.github.io/fuga-de-resonancia/manifest.json'
          package_id: 'com.munddev.fugaresonancia'
          name: 'Fuga de Resonancia 1.2'
          app_version: '1.2.0'
          
      - name: Subir APK
        uses: actions/upload-artifact@v4
        with:
          name: FugaResonancia-v1.2-APK
          path: pwabuilder-release.apk
